### ISSUE TITLE
Cannot install operator as normal user (cannot create operatorgroup)

### ISSUE THREAD

**Issue by nicolaferraro** [operator-framework/operator-lifecycle-manager#1286] opened 2020-02-10 13:54 UTC
## Bug Report

**What did you do?**

I've created a new OpenShift user with no special permissions.
Logged in with that user, I create a new namespace and I want to install an operator locally (Camel K). I create a Subscription to the "camel-k" package. Creation goes well, but the UI reports the error: 

```
Failed: csv in namespace with no operatorgroups
```

I try to create an operatorgroup targeting the local namespace only and I get the error:

```
operatorgroups.operators.coreos.com is forbidden: User "nicola" cannot create resource "operatorgroups" in API group "operators.coreos.com" in the namespace "olm-tests"
```

So standard users can create subscriptions and CSV but not operatorgroups. So they are unable to install a package, unless someone else creates the operatorgroup with higher privileges (e.g. by installing and uninstalling the same package via operator hub).

**What did you expect to see?**

I should be able to create operatorgroups by default, or having them created automatically when I want a local operator.

**What did you see instead? Under which circumstances?**

There's no clear way to enable a normal user to install operators.

**Environment**
* operator-lifecycle-manager version:

`quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0c4b5c9623030edd9d7cf55809f1a43aa64be739038f275d2bf737e5b2c793a0`

* Kubernetes version information:

```
oc v3.11.0+06cfa24-67
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.camel-k.rhmw-integrations.net:6443
kubernetes v1.14.6+20e2756
```

* Kubernetes cluster kind: 

OpenShift 4.2

**Comment by exdx** [comment] 2020-02-10 17:52
Hi @nicolaferraro, so this behavior is actually expected: cluster admins are the ones that are installing operators in the cluster, and regular users are then able to create the CRs associated with them. This is because operators are cluster-scoped resources and installing them introduces new CRDs in the cluster. "There's no clear way to enable a normal user to install operators." is the current default behavior of OLM, since operators can fundamentally change the behavior of a cluster, only cluster-admins are expected to be able to deploy them.

**Comment by awgreene** [comment] 2020-02-10 18:01
Given that this is expected behavior, I will be closing this issue. @nicolaferraro please reopen the issue if you wish to continue the conversation.

**Closed by awgreene** 2020-02-10 18:01 UTC

**Comment by cdjohnson** [comment] 2021-04-22 13:02
Not sure when this happened, but the creation of an OperatorGroup and Subscription has been decoupled.
https://docs.openshift.com/container-platform/4.7/operators/admin/olm-creating-policy.html

In short:  
1. A Cluster Admin creates an OperatorGroup and the ServiceAccount for OLM to impersonate within that OperatorGroup.
2. A Namespace Admin creates a Subscription within the namespace managed by the pre-created OperatorGroup.

So, there is a clear pattern on how Namespace Admins can create Subscriptions
