### ISSUE TITLE
is ARM architecture supported by OLM?

### ISSUE THREAD

**Issue by EpiqSty** [operator-framework/operator-lifecycle-manager#1138] opened 2019-11-17 18:43 UTC
## Question

**What did you do?**
I am trying to deploy OLM by : 
```
kubectl create -f deploy/upstream/quickstart/crds.yaml
kubectl create -f deploy/upstream/quickstart/olm.yaml
```

**What did you expect to see?**
olm pods running

**What did you see instead? Under which circumstances?**
```
# kubectl get all -o wide -A  | grep olm
olm                    pod/catalog-operator-864f76ddbd-vjkbw            0/1     CrashLoopBackOff   1          36s     10.42.0.34   rpi-master   <none>           <none>
olm                    pod/olm-operator-77ccc89d8f-knn8j                0/1     CrashLoopBackOff   2          36s     10.42.1.33   rpi-screen   <none>           <none>
olm                    deployment.apps/olm-operator                0/1     1            0           36s   olm-operator                quay.io/operator-framework/olm:latest    app=olm-operator
olm                    deployment.apps/catalog-operator            0/1     1            0           36s   catalog-operator            quay.io/operator-framework/olm:latest    app=catalog-operator
olm                    replicaset.apps/catalog-operator-864f76ddbd            1         1         0       36s   catalog-operator            quay.io/operator-framework/olm:latest    app=catalog-operator,pod-template-hash=864f76ddbd
olm                    replicaset.apps/olm-operator-77ccc89d8f                1         1         0       36s   olm-operator                quay.io/operator-framework/olm:latest    app=olm-operator,pod-template-hash=77ccc89d8f
```

**Environment**
* operator-lifecycle-manager version:

```
# grep image olm.yaml
          image: quay.io/operator-framework/olm:latest
          imagePullPolicy: IfNotPresent
          image: quay.io/operator-framework/olm:latest
          imagePullPolicy: IfNotPresent
                image: quay.io/operator-framework/olm@sha256:91ac5bf350192e063a3c1be994827f67e254997939eda3d471253777cc840c45
                imagePullPolicy: Always
  image: quay.io/operator-framework/upstream-community-operators:latest
```

* Kubernetes version information:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/arm"}
```
  

* Kubernetes cluster kind: 
```
 k3s --version
k3s version v0.10.2 (8833bfd9)
```
**Additional context**
in the pod log:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
which typically indicates  X86_64 build trying to execute at ARM

So, the question is there any ability to get OLM running at ARM at all?

**Comment by ecordell** [comment] 2019-11-17 22:51
Arm is supported but the manifests that we provide in releases reference x86 images. 

We will look into setting up builds for arm images - in the meantime you can build them yourself fairly easily. Take a look at our Dockerfile and swap the baseimage for an arm one with go tooling and you should be good - `make build` will use whatever go os/arch is configured).

**Comment by kimba74** [comment] 2021-01-04 00:56
> Arm is supported but the manifests that we provide in releases reference x86 images.
> 
> We will look into setting up builds for arm images - in the meantime you can build them yourself fairly easily. Take a look at our Dockerfile and swap the baseimage for an arm one with go tooling and you should be good - `make build` will use whatever go os/arch is configured).

Has anything ever come out of this? I saw in the code that ARM was supported but it doesn't look like there are any ARM based images for the OLM out there, yet.

@ecordell do you have any recommendations for ARM base images with Go tooling?

Thanks in advance for your help.

**Comment by Projoke** [comment] 2021-02-26 01:20
Meet the same question, waiting for image update for ARM64 platform.

**Comment by DWSR** [comment] 2021-03-05 04:03
Would also love to see ARM support for my Pi cluster

**Comment by ChampiYann** [comment] 2021-05-05 11:25
While we wait on the builds here are the steps I took to get it working on my raspberry pi 4 cluster:

- pull the repo
- in `upstream.Dockerfile`, change the fedora builder base image to the **aarch64** version. 
Basically replace `FROM quay.io/fedora/fedora:34-x86_64 as builder` with `FROM quay.io/fedora/fedora:34-aarch64 as builder`
- run `docker build -f upstream.Dockerfile -t <insert tag> .`
- push the image to my registry
- in `deploy/upstream/quickstart/olm.yaml`, change `quay.io/operator-framework/olm@sha256:e9de77ac5c08643202ad42a0311d15c98ffbfd8a1dc2eab4e9f2dcaeed7110ac` to the reference to the image you just pushed

You should now be able to apply the `deploy/upstream/quickstart/crds.yaml` and `deploy/upstream/quickstart/olm.yaml` as per the installation instructions.

**Comment by clayrisser** [comment] 2021-05-08 13:34
When I deploy the operator lifecycle manager on an arm server, the operator runs just fine. However it creates some other pods (for example the packageserver) using the image from quay.io, which obviously won't work on arm. How do I force the operator to run the packageserver pod using my arm built image?

**Comment by ChampiYann** [comment] 2021-05-08 16:12
It should be mentioned in de `olm.yaml` file. I changed a few references to my own build images.

**Comment by clayrisser** [comment] 2021-05-09 02:57
@ChampiYann I can’t find an olm.yaml file. What folder is it in?

**Comment by ionutz89** [comment] 2021-05-11 14:43
> @ChampiYann I can’t find an olm.yaml file. What folder is it in?

You can find here the [file](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/quickstart/olm.yaml)

Does someone have a multi-arch image for `quay.io/operatorhubio/catalog:latest`

I could not manage to build myself an image. I think it should be automatically to multi arch.

**Comment by jli3388** [comment] 2021-08-03 05:52
@ChampiYann  I tried to use ur operator in a pi cluster but it failed with the usual exec format error. 
I used "image: rosemay/community-operator:arm".
Please let me know if I am doing something wrong.  I am about to pull a linux image and try podman... I am on a mac.

**Comment by draeron** [comment] 2021-09-06 17:34
considering this issue is open since 2019 I wouldn't get any hope it will be supported any time soon.

**Comment by timflannagan** [comment] 2021-09-06 20:20
@joelanford Any idea on whether we'd need to simply also integrate your goreleaser work in the registry into OLM for OLM support on ARM? Would we need to change the Dockerfiles at all either?

**Comment by jeevanjoseph** [comment] 2021-09-24 17:28
Not having Arm images can lead to worse issues when clusters have both Arm and x86 nodes. Rather than fail outright in a pure arm based cluster, it will work when the scheduler picks x86 nodes for these pods, but fail if by chance it gets scheduled on an arm64 node. In the meantime, if `arm64` support needs more discussion, can the charts add some nodeSelector with well known labels like `kubernetes.io/arch=amd64` could be a temporary workaround ?

**Comment by timflannagan** [comment] 2021-09-24 18:16
I spent some time last Friday trying to integrate goreleaser for this repository to streamline the release process for this project - that should give us a chance to produce multi-arch binaries, container images, and manifestlists as part of that effort. I still need to wrap my head around the final product, but I'm thinking it's likely we'll have arm64/amd64 tagged OLM images, along with a manifestlist image for minor version tags (with the latest tag on the horizon as there's some complexity there).

**Comment by timflannagan** [comment] 2021-09-27 17:41
Alright, I just published quay.io/operator-framework/olm:v0.19.1 and quay.io/operator-framework/olm:v0.19 which are both manifestlist images that contain arm64/amd64/s90x/ppc64le multi-arch container images in preparation of the 0.19 minor release. Would anyone be able to test out whether those image(s) work on ARM-based clusters, and whether CRI pulls the correct architecture?

**Comment by jbpratt** [comment] 2021-09-27 18:04
@timflannagan just gave it a try, things are looking good! This is on an aarch64 (RPi) cluster. It seems that the operatorhubio/catalog image doesn't have an associated manifest, though I don't think it is directly related to this issue. Awesome stuff!

```
❯ oc get pods -n olm
NAME                              READY   STATUS             RESTARTS   AGE
catalog-operator-68d788f4-vkl89   1/1     Running            0          2m53s
olm-operator-6cbcdd9576-598vl     1/1     Running            0          3m46s
operatorhubio-catalog-hmgsv       0/1     CrashLoopBackOff   4          2m47s
packageserver-674799bb95-56ztx    1/1     Running            0          22s
packageserver-674799bb95-cszst    1/1     Running            0          22s
```

```
❯ oc logs -n olm pod/operatorhubio-catalog-hmgsv
standard_init_linux.go:228: exec user process caused: exec format error
```

```
❯ podman manifest inspect quay.io/operatorhubio/catalog:latest
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "config": {
        "mediaType": "application/vnd.docker.container.image.v1+json",
        "size": 3688,
        "digest": "sha256:cab5d107d4bdd47efaf2df62f2c3d194a248c69af29271c6c0aceb9dc6d6fad4"
    },
    "layers": [
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 2813006,
            "digest": "sha256:29291e31a76a7e560b9b7ad3cada56e8c18d50a96cca8a2573e4f4689d7aca77"
        },
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 2441601,
            "digest": "sha256:5140b3a86fae096a58fa267c6fd7ba95b58fdb211633cd2e0d513cfbb435ea35"
        },
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 169,
            "digest": "sha256:3f64a6388cf7c7a07bb47425fd3e0ca8c1fc03ae41996d41feef2d28347935d7"
        },
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 16171058,
            "digest": "sha256:3c43e60f6949ce8f8b149c77b467686f6acd56c85cfbc1e71607efda477a46b5"
        },
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 3776660,
            "digest": "sha256:37c49b312d635a330d5aed30f73778c565c35823e99342fa2695ff8ff2ddbf43"
        },
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 26335286,
            "digest": "sha256:c213f7ceaa8003dcf19c49402162b8eab8ec85cda71b78529307c9868a26d363"
        }
    ]
}
```

**Comment by jeevanjoseph** [comment] 2021-09-27 20:10
@timflannagan - I can confirm the same results as @jbpratt on an OCI cluster with Ampere Altra based nodes.  Only `operatorhubio/catalog` is failing because it does not have a manifest list image. 

```
kubectl get pods -n olm
NAME                                READY   STATUS             RESTARTS   AGE
catalog-operator-69f7ffbc74-mkgcd   0/1     CrashLoopBackOff   2          35s
olm-operator-6cbcdd9576-4tc5s       1/1     Running            0          36s
packageserver-55dcc7f96f-9rv2h      1/1     Running            0          29s
packageserver-55dcc7f96f-zxrl7      1/1     Running            0          29s
```

My x86 nodes are cordoned. 
```
kubectl get nodes -o wide
NAME          STATUS                     ROLES   AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION                       CONTAINER-RUNTIME
10.0.10.11    Ready                      node    4d1h   v1.20.8   10.0.10.11    <none>        Oracle Linux Server 7.9   5.4.17-2102.204.4.4.el7uek.aarch64   cri-o://1.20.2
10.0.10.161   Ready,SchedulingDisabled   node    4d2h   v1.20.8   10.0.10.161   <none>        Oracle Linux Server 7.9   5.4.17-2102.204.4.4.el7uek.x86_64    cri-o://1.20.2
10.0.10.19    Ready                      node    4d1h   v1.20.8   10.0.10.19    <none>        Oracle Linux Server 7.9   5.4.17-2102.204.4.4.el7uek.aarch64   cri-o://1.20.2
10.0.10.190   Ready,SchedulingDisabled   node    4d2h   v1.20.8   10.0.10.190   <none>        Oracle Linux Server 7.9   5.4.17-2102.204.4.4.el7uek.x86_64    cri-o://1.20.2
10.0.10.243   Ready                      node    4d1h   v1.20.8   10.0.10.243   <none>        Oracle Linux Server 7.9   5.4.17-2102.204.4.4.el7uek.aarch64   cri-o://1.20.2
10.0.10.42    Ready,SchedulingDisabled   node    4d2h   v1.20.8   10.0.10.42    <none>        Oracle Linux Server 7.9   5.4.17-2102.204.4.4.el7uek.x86_64    cri-o://1.20.2
```

**Comment by timflannagan** [comment] 2021-09-27 20:13
@jeevanjoseph @jbpratt  Awesome, thanks for testing that out.

@jeevanjoseph Any idea on why that catalog-operator is reporting a CrashLoopBackOff status?

**Comment by ChampiYann** [comment] 2021-09-27 20:30
I think it's the same problem as this issue: there is not arm version of the container image.

> > Does someone have a multi-arch image for `quay.io/operatorhubio/catalog:latest`
> > I could not manage to build myself an image. I think it should be automatically offered as an official multi-arch since more vendors are providing ARM64 support.
> 
> That's a tricky one. I created an image for ARM64 only which you can find here: https://hub.docker.com/repository/docker/rosemay/community-operator
> 
> We should really discuss this in it's dedicated repo: https://github.com/operator-framework/community-operators
> Or it's parent registry builder repo: https://github.com/operator-framework/operator-registry
> 
> Not sure which one is best

**Comment by jeevanjoseph** [comment] 2021-09-27 20:36
Sorry - that was my mistake - I also assumed it to be `quay.io/operatorhubio/catalog` without reading it well... Its `catalog-operator` and its failing because I missed updating the image and config for `catalog-operator` in `deploy/upstream/quickstart/olm.yaml`.

**Comment by sxd** [comment] 2021-10-04 14:22
Hi everyone, the new release of operator-registry now supports multi-arch in the container images the support was added on Sep 30 and the release was 3 days ago.
This is the commit: https://github.com/operator-framework/operator-registry/commit/943a9a110ef938e26ec9d15a4a9724fb0601c51e

**Comment by timflannagan** [comment] 2021-10-11 13:35
Thanks everyone for the help with testing the latest release that attempted to add linux multi-arch support - it looks like we're now waiting on the operatorhub catalogsource image to be multi-arch compatible: https://github.com/k8s-operatorhub/community-operators/issues/262.

Going to close this issue out in the meantime.

**Closed by timflannagan** 2021-10-11 13:35 UTC
Labels: triaged

**Comment by aimichelle** [comment] 2023-01-26 21:51
Hi @timflannagan , would it be possible to merge in https://github.com/operator-framework/operator-lifecycle-manager/pull/2896? OLM currently doesn't work on ARM, and results in these bugs since the wrong version of `cp` binary is included: https://github.com/operator-framework/operator-lifecycle-manager/issues/2861 https://github.com/operator-framework/operator-lifecycle-manager/issues/2769

**Comment by vihangm** [comment] 2023-02-07 22:40
@awgreene can we get a minor version released with the platform fix? we could build our own version of the image as a workaround but it would be nicer to just continue using the OLM images.

**Comment by awgreene** [comment] 2023-02-08 13:43
@vihangm that seems reasonable, I'll make sure a new version is cut shortly.

**Comment by aimichelle** [comment] 2023-03-10 18:52
@awgreene , we just wanted to check in again. Do you know when the release will be cut? We're super excited to start using OLM on ARM.

**Comment by awgreene** [comment] 2023-03-13 14:54
Sorry for the delay, the [v0.24.0 tag](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.24.0) has been cut and should be available as a release shortly @aimichelle.

**Comment by vihangm** [comment] 2023-03-13 17:31
The [releaser](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/4406264215) failed, looks like the `goreleaser` action needs QEMU installed so that the busybox binaries can be emulated.
Adding `docker/setup-qemu-action@v2` to the releaser should probably fix it.

**Comment by awgreene** [comment] 2023-03-13 19:17
@vihangm seems like you're correct, I started a PR [here](https://github.com/operator-framework/operator-lifecycle-manager/pull/2936), but I haven't used QEMU before. Any links / suggestions?

**Comment by awgreene** [comment] 2023-03-13 19:23
This [blog post](https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/) seems to provide a good summary.

**Comment by vihangm** [comment] 2023-03-13 20:00
Yup, just adding QEMU should suffice I believe. That will allow system emulation of aarch64 (and other architectures) and so the docker build should work again.

**Comment by awgreene** [comment] 2023-03-13 22:49
Perfect, I've tested it [here](https://github.com/awgreene/operator-lifecycle-manager/actions/runs/4410163118/jobs/7727334061) as well, binaries were built successfully, job failed due to missing credentials. The PR above should be good to go.

**Comment by agelwarg** [comment] 2023-03-14 20:52
Looks like v0.24.0 release addressed issue with the `quay.io/operator-framework/olm` image for ARM with incorrect `cp` binary, but next up we have an issue with the `quay.io/operator-framework/upstream-opm-builder` image

`exec /bin/opm: exec format error`
