### ISSUE TITLE
Attempting upstream installation against kube >= 1.11 fails with validation errors

### ISSUE THREAD

**Issue by marun** [operator-framework/operator-lifecycle-manager#400] opened 2018-07-27 19:46 UTC
I invoked `kubectl apply -f deploy/upstream/manifests/0.5.0` as per the installation instructions.  I see the same errors with minikube supplied with `--kubernetes-version v1.11.0` and running `hack/local-up-cluster.sh` against kube master.  `0.4.0` has the same problem.

```
error validating "deploy/upstream/manifests/0.5.0/03-clusterserviceversion.crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.customresourcedefinitions.properties.owned.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.customresourcedefinitions.properties.required.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.icon.properties.mediatype.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.icon.properties.mediatype.enum[1]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.icon.properties.mediatype.enum[2]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.icon.properties.mediatype.enum[3]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[0].properties.strategy.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[1].properties.spec.properties.deployments.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[1].properties.spec.properties.permissions.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[1].properties.strategy.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.keywords.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.links.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maintainers.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[1]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[2]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[3]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[4]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[5]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[6]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[7]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.selector.properties.matchExpressions): unknown field "descriptions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.selector.properties.matchExpressions.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected ""]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "deploy/upstream/manifests/0.5.0/05-catalogsource.crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.configMap): unknown field "string" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.secrets.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.sourceType.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected ""]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "deploy/upstream/manifests/0.5.0/06-installplan.crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.anyOf[0]): unknown field "approval" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.anyOf[1]): unknown field "approval" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.approval.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.approval.enum[1]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.approval.enum[2]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.clusterServiceVersionNames.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected ""]; if you choose to ignore these errors, turn validation off with --validate=false
```

What version(s) of kubernetes are known to support installation of olm?

**Comment by ecordell** [comment] 2018-07-27 21:40
Thanks @marun! We're working through these issues right now - you can track them in this #398

**Comment by ecordell** [comment] 2018-07-28 14:08
I believe those specific errors are bugs in the client side validation that kubectl does. Everything should work as intended if you create with `--validate=false` for now.

**Comment by ecordell** [comment] 2018-08-03 00:14
@marun These issues should be fixed in master, please re-open if you find that they're not!

**Closed by ecordell** 2018-08-03 00:14 UTC
