### ISSUE TITLE
How often releases cut?

### ISSUE THREAD

**Issue by csantanapr** [operator-framework/operator-lifecycle-manager#1415] opened 2020-03-30 03:57 UTC
I'm installing on a none OpenShift cluster in my case IBM Cloud IKS

I'm currently using release as stable steps to update/install

I noticed that latest release is 0.14.1 from Jan 30, 2020

There are 111 commits since this release on master, are there plans to cut a release tag soon?
https://github.com/operator-framework/operator-lifecycle-manager/compare/0.14.1...master

**Comment by kramvan1** [comment] 2020-04-27 21:51
@ecordell Any idea on when a new release is coming out, there are now CVE issues with the 0.14.1 images.

**Comment by ecordell** [comment] 2020-04-27 21:59
We will cut a release once #1470 is merged - it's a regression that shouldn't make it into a release.

**Comment by kramvan1** [comment] 2020-04-27 22:15
@ecordell Thx for the update.

**Comment by kramvan1** [comment] 2020-05-13 14:47
@ecordell  Hi, any news on new releases, I see tags for 014.2 and 15.0.

**Comment by kfox1111** [comment] 2020-05-16 15:37
Out of the box, olm's often broken for me right now due to the OOM issue.

**Comment by anik120** [comment] 2020-06-04 20:40
Hi @csantanapr, the latest release of olm is [v0.15.1](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/0.15.1)

**Closed by anik120** 2020-06-04 20:40 UTC
