### ISSUE TITLE
Subscription with empty resource config will overwirte operator deployment resource

### ISSUE THREAD

**Issue by hangyan** [operator-framework/operator-lifecycle-manager#1953] opened 2021-01-13 03:42 UTC
## Bug Report

**What did you do?**
Just install the olm

**What did you expect to see?**
the builtint packageserver operator with resources settings in it's csv and i hoping to see it in the actual deployment
<img width="836" alt="image" src="https://user-images.githubusercontent.com/3939015/104403766-335a2a80-5594-11eb-884f-755a7179528b.png">

**What did you see instead? Under which circumstances?**
packageserver deployment with empty resoruce
<img width="617" alt="image" src="https://user-images.githubusercontent.com/3939015/104403800-440aa080-5594-11eb-87e0-33f338e5729c.png">

**Environment**
* operator-lifecycle-manager version:  

0.17.0

* Kubernetes version information:

v1.16.9

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**
I installl some of my own operators, same thing happend

**Comment by matskiv** [comment] 2021-01-28 15:25
This looks like a duplicate of #1912

**Closed** 2021-03-04 17:28 UTC
Labels: kind/bug
