### ISSUE TITLE
v0.23.0 break operators installation

### ISSUE THREAD

**Issue by cedvan** [operator-framework/operator-lifecycle-manager#2914] opened 2023-01-11 17:25 UTC
## Bug Report

**Environment**
* operator-lifecycle-manager version: v0.23.0
* Cluster type : k3s (from truenas scale)
* Kubernetes version information: v1.25.3+k3s-9afcd6b9-dirty

**Problem**

Just install a fresh operator lifecycle manager to new truenas scale server.

* Install [Operator SDK CLI](https://sdk.operatorframework.io/docs/installation/)
* Install OLM : `operator-sdk olm install` (default last, so v0.23.0)
* Create [cert-manager operator](https://operatorhub.io/operator/cert-manager) : `kubectl create -f https://operatorhub.io/install/cert-manager.yaml` => create successfull
* My cert manager operator never up and result command `kubectl get csv -n operators` stay empty. `operators` namespace stay as no resources.

**Temporary solution**

Uninstall `v0.23.0` and force install v0.22.0 with `--version v0.22.0`. Recreate cert-manager operator, and my cert manager up :)

**Conclusion**

Version v0.23.0 break operator installation

**Comment by awgreene** [comment] 2023-01-11 17:48
Ah, this is happening because the community catalogSource isn't being ran in restricted mode, which is fixed in [this PR](https://github.com/operator-framework/operator-lifecycle-manager/pull/2915).

**Comment by debovema** [comment] 2023-01-12 15:02
Same here.
Thank you for the fix, which can be applied directly:
```
kubectl patch catalogsources.operators.coreos.com -n olm operatorhubio-catalog --type merge --patch '{"spec":{"grpcPodConfig":{"securityContextConfig":"restricted"}}}'
```

**Comment by awgreene** [comment] 2023-01-12 17:08
The `v0.23.1` release fixes this issue. I've marked the `v0.23.0` release with a warning.

**Closed by awgreene** 2023-01-12 17:08 UTC
Labels: kind/bug

**Comment by leochr** [comment] 2023-01-12 22:12
@awgreene We are trying to understand the root cause of this problem because this is also affecting our CatalogSource. Is patching of the catalog sources a temporary workaround? Would OLM be updated to handle the CatalogSource (without the `restricted` mode) differently in the future so it doesn't fail? FYI @git4rk @pbaity
