### ISSUE TITLE
FailedCreate   replicaset/catalog-operator and replicaset/olm-operator

### ISSUE THREAD

**Issue by kirankumar-mahi** [operator-framework/operator-lifecycle-manager#1586] opened 2020-06-22 05:24 UTC
Hi There,

I am not able to install OLM 0.15.1 on the Kubernetes cluster 1.18.4

Steps executed - > 

Step1 -

$ curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.15.1/install.sh | bash -s 0.15.1

failed with errors. 

Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...
Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...
error: deployment "olm-operator" exceeded its progress deadline

olm         2s          Warning   FailedCreate        replicaset/catalog-operator-67f885b8f5   Error creating: Timeout: request did not complete within requested timeout 34s
olm         77s         Warning   FailedCreate        replicaset/catalog-operator-67f885b8f5   Error creating: Timeout: request did not complete within requested timeout
olm         9m13s       Normal    ScalingReplicaSet   deployment/catalog-operator              Scaled up replica set catalog-operator-67f885b8f5 to 1
olm         2s          Warning   FailedCreate        replicaset/olm-operator-665576bb4        Error creating: Timeout: request did not complete within requested timeout 34s
olm         9m13s       Normal    ScalingReplicaSet   deployment/olm-operator                  Scaled up replica set olm-operator-665576bb4 to 1 

Environment ->

1. operator-lifecycle-manager release 0.15.1

1. go version go1.14.4 linux/amd64

2. Kubectl version :

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

3. uname -a ->

Linux <hostname> 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by exdx** [comment] 2020-06-23 19:52
Kind of hard to tell what's going on based on these logs -- is it possible the pod was not able to be scheduled? 

I know it's kind of tricky, but is there any more information that you can provide us with? Was this a local cluster or in the cloud? We run our e2e tests on kind clusters to capture upstream kube-related issues, so issues like this one are important to us. OLM should be able to install and run just fine on vanilla kube.

**Comment by kirankumar-mahi** [comment] 2020-06-25 17:07
Its failure creating replicaset. This happened in kubernetes 1.18.4 version. But when I downgraded version to kubernetes 1.18.0 it worked.

**Comment by timflannagan** [comment] 2022-02-11 19:42
It looks like we don't have enough information to debug this failed installation further, so I'm going to close this out in the meantime. Let's re-open this if we can reproduce this failure using newer OLM minor version releases, and attach any necessary debugging information then.

**Closed by timflannagan** 2022-02-11 19:42 UTC
Labels: kind/bug, triage/unresolved, triage/needs-information
