### ISSUE TITLE
Olm install is broken due to 0.29.0

### ISSUE THREAD

**Issue by basvdlouw** [operator-framework/operator-lifecycle-manager#3435] opened 2024-11-07 09:14 UTC
## Bug Report

`operator-sdk olm install` by default installs the "latest" release, but the "latest" release is broken (0.29.0) and the artifacts are removed. Therefore `operator-sdk olm install` fails. In my opinion the latest tag should be put back on 0.28.0 so that the install command works by default. (Or use a different tag than latest)

**What did you do?**

`operator-sdk olm install`

**What did you expect to see?**

OLM installation of the latest stable version

**What did you see instead? Under which circumstances?**

```
operator-sdk olm install           
INFO[0000] Fetching CRDs for version "latest"           
INFO[0000] Fetching resources for resolved version "latest" 
FATA[0000] Failed to install OLM version "latest": failed to get resources: failed to fetch CRDs: request failed: failed GET 'https://github.com/operator-framework/operator-lifecycle-manager/releases/latest/download/crds.yaml': unexpected status code 404, expected 200; manifests may not exist for this OLM release,please check https://github.com/operator-framework/operator-lifecycle-manager/releases for olm.yaml and crds.yaml 
```

**Environment**
* operator-lifecycle-manager version:
0.29.0

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

operator-sdk olm install should point to the latest stable version, not a broken release

**Additional context**

**Comment by jmazzitelli** [comment] 2024-11-08 12:15
this appears to be a dup of: https://github.com/operator-framework/operator-lifecycle-manager/issues/3419

A release of 0.30.0 is imminent, from what I understand.

**Comment by m1kola** [comment] 2024-11-12 10:02
Yes. Closing as a duplicate of #3419

**Closed by m1kola** 2024-11-12 10:02 UTC
Labels: kind/bug
