### ISSUE TITLE
The layout of https://olm.operatorframework.io/docs/ is broken

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#1919] opened 2020-12-23 11:23 UTC
## Bug Report

**What did you do?**
Check https://olm.operatorframework.io/docs/ 

**What did you expect to see?**
The lateral menu

**What did you see instead? Under which circumstances?**
<img width="904" alt="Screen Shot 2020-12-23 at 11 21 41" src="https://user-images.githubusercontent.com/7708031/102991497-37ed6f00-4511-11eb-8e04-ca7d114eb5ab.png">

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by matthewcarleton** [comment] 2021-01-15 19:11
@camilamacedo86 can you provide the OS/browser you are seeing this in?

**Comment by anik120** [comment] 2021-01-15 19:29
@matthewcarleton I'm seeing this on fedora 33/chrome 
Note that this issue is not there when the browser is extended and takes up the full screen. It only happens when the size of the browser starts to get reduced. 

I've heard similar feedback from users on mac os/chrome too.

**Comment by anik120** [comment] 2021-01-15 19:32
It can also be reproduced by zooming in on the page. 
Things seem fine till the page in my browser is zoomed in till 125%. As soon as I go to 150% this starts happening.

**Comment by camilamacedo86** [comment] 2021-01-15 19:42
Hi folks, 

I use chrome in a mac. WDYT about we push the layout config from https://github.com/operator-framework/operator-sdk/tree/master/website to the olm-docs? I think it would solve this problem and others as ensure that all have the same appearance.

**Comment by anik120** [comment] 2021-01-15 20:52
I'm all for both the sites looking the same. We might wanna be a little careful in adding whatever's there in https://github.com/operator-framework/operator-sdk/tree/master/website though since some of the decisions made for the sdk doc site were different than the olm site. The one to concern ourselves with here is that sdk decided not to expand the menu on the left nav panel, whereas olm decided to expand it, which is why we see the scroll bar. And it's the scroll bar that's causing the problem here as far as I can tell.

**Comment by anik120** [comment] 2021-01-15 21:00
/close
fixed by https://github.com/operator-framework/olm-docs/pull/92

**Closed by anik120** 2021-01-15 21:00 UTC
Labels: kind/bug
