### ISSUE TITLE
Users should be able to provide a imagePullSecret when installing the Operator using OLM

### ISSUE THREAD

**Issue by srinivasannanduri** [operator-framework/operator-lifecycle-manager#1821] opened 2020-10-20 13:43 UTC
## Feature Request

When using private registries to store images, using these images requires a secret and the secret to be configured as imagePullSecret to pull operator images. However, OLM today do not provide a way for users to provide an `imagePullSecret` to be used to pull the images

**Describe the solution you'd like**
OLM should provide a way for users to provide an imagePullSecret during installation of an Operator from the Operator Catalog

**Comment by exdx** [comment] 2020-10-22 18:32
Hi @srinivasannanduri, the CatalogSource CRD has a field on its spec called `Secrets`, which is an array of secret names that can be used for pulling operator images during the installation process (see https://github.com/operator-framework/api/blob/00315468e812212e3c893c469bae957251ae0308/crds/operators.coreos.com_catalogsources.yaml#L106). These secrets will be copied into the operator namespace and then used when pulling the image. Could you try adding the secrets there and see if that resolves your issue? 

This is also mentioned in https://olm.operatorframework.io/docs/tasks/troubleshooting/catalogsource/#my-catalogsource-cannot-pull-images-from-a-private-registry

**Comment by awgreene** [comment] 2020-12-10 15:02
It looks like this is a dupe of https://github.com/operator-framework/operator-lifecycle-manager/issues/1536 which has recently been fixed.

**Closed by awgreene** 2020-12-10 15:02 UTC
Labels: triage/support
