### ISSUE TITLE
Getting started guide does not work

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-lifecycle-manager#677] opened 2019-01-21 10:11 UTC
Having deployed OLM, I created a memcached cvs. After that, created crd and rbac. However, operator is flagged as failed:

![image](https://user-images.githubusercontent.com/5337267/51467605-9504a700-1d75-11e9-8c46-9d6252bccd3d.png)

Where can I find a reason for this failure?

**Comment by ecordell** [comment] 2019-01-21 13:58
Hi @eivantsov - if you click on the name of the failed install you should see details about what failed.

The easiest way is to `kubectl get csv memcache -o yaml` and look at it status block. 

Since I see that you're running locally, I imagine the failure is because we configure OLM differently than normal when run locally; you may need to put your CSVs into `local-operators` for them to work.

**Comment by eivantsov** [comment] 2019-01-21 16:16
That's what I did, and previously the status showed reasons for a failed status. Now, I am trying the same thing again and cannot see status block at all.

**Comment by eivantsov** [comment] 2019-01-21 17:48
I have tried with different csv like prometheus, etcd etc. Same result, there's no status and nothing happens in the namespace. 

Could you give me some pointers/hints on what I might be doing wrong and how to debug it?

**Comment by ecordell** [comment] 2019-01-22 13:47
Can you explain how you deployed OLM? To me it seems that OLM is not configured to watch the namespace you’re creating resources in. 

If you could share the olm-operator deployment that would be very helpful

**Comment by eivantsov** [comment] 2019-01-22 13:50
This time, it's OpenShift 4.0, so it was deployed as part of installation I suppose. Which exact deployment is in question?

![image](https://user-images.githubusercontent.com/5337267/51539756-7548ae00-1e5d-11e9-9ddc-4e20711d8855.png)

**Comment by ecordell** [comment] 2019-01-22 13:57
What version of the installer?

I think the issue is that you should be creating CSVs in the
‘openshift-operators’ namespace, so that they get associated with the
‘global-operators’ operatorgroup.

We recently merged some changes that provide good error messages in this
case (telling you about the operatorgroup issue). They should be in master
of openshift if that’s an option for you.

**Comment by eivantsov** [comment] 2019-01-22 14:02
That I don't know - it was installed like a week ago, probably built from master.

Creating csv in openshift-operator namespace has the same effect, ie no effect.

**Comment by eivantsov** [comment] 2019-01-22 14:34
@ecordell update. Installer version 0.9.1

But I have the same results when deploying the latest OLM in OKD 3.11.

**Comment by eivantsov** [comment] 2019-01-22 15:25
```
time="2019-01-22T15:23:49Z" level=info msg="getting from queue" key=openshift-operators/cheoperator.v0.0.1 queue=/clusterserviceversions
--
  | time="2019-01-22T15:23:49Z" level=info msg="not in operatorgroup namespace, skipping" csv=cheoperator.v0.0.1 namespace=openshift-operators
```
Wrong namespace?

**Comment by eivantsov** [comment] 2019-01-22 15:44
@ecordell I am trying a different namespace:

```

time="2019-01-22T15:41:25Z" level=info msg="openshift-operator-lifecycle-manager/cheoperator.v0.0.1 added"
--
  | time="2019-01-22T15:41:25Z" level=info msg="getting from queue" key=openshift-operator-lifecycle-manager/cheoperator.v0.0.1 queue=/clusterserviceversions
  | time="2019-01-22T15:41:25Z" level=info msg="not in operatorgroup namespace, skipping" csv=cheoperator.v0.0.1 namespace=openshift-operator-lifecycle-manager phase=
  | time="2019-01-22T15:41:25Z" level=warning msg="installmodes not supported" csv=cheoperator.v0.0.1 err="SingleNamespace InstallModeType not supported, cannot configure to watch one namespace" namespace=openshift-operator-lifecycle-manager opgroup=olm-operators phase=
```

**Comment by eivantsov** [comment] 2019-01-23 07:42
The solution was to add:

```
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: true
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
```

However, memcached example in the Getting Started guide does not have install modes. Should it perhaps be updated or it's me who's doing smth wrong?

**Comment by ecordell** [comment] 2019-01-23 13:44
The getting started guide was written for 3.11 - we definitely need to
update it for 4.0

**Comment by eivantsov** [comment] 2019-01-23 13:55
@ecordell i got it to work on 3.11 :)
1. Install OKD 3.11
2. Deploy OLM
3. Try memcached csv

**Closed** 2019-05-30 20:38 UTC
