### ISSUE TITLE
 Operator Group [It] insufficient permissions resolve via RBAC

### ISSUE THREAD

**Issue by stevekuznetsov** [operator-framework/operator-lifecycle-manager#3111] opened 2023-11-14 15:18 UTC
```
 Operator Group [It] insufficient permissions resolve via RBAC
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:1612

  Timeline >>
  created the operator-group-e2e-smz2l testing namespace
  14:29:40.0142: Creating CRD
  14:29:40.0197: Creating operator group
  14:29:40.0248: Creating CSV
  14:29:40.0395: wait for CSV to fail
  14:29:40.2316:  (): 
  waited 10.217669861s for CSV operator-group-e2e-smz2l-vv7fx/another-csv-xtrdv: to be in phases [Failed], in phase  (): 
  14:29:40.4316:  (): 
  14:29:40.6312:  (): 
  14:29:40.8311:  (): 
  14:29:41.0321:  (): 
  14:29:41.2321: Pending (RequirementsUnknown): requirements not yet checked
  waited 1.000538645s for CSV operator-group-e2e-smz2l-vv7fx/another-csv-xtrdv: to be in phases [Failed], in phase Pending (RequirementsUnknown): requirements not yet checked
  14:29:41.4312: InstallReady (AllRequirementsMet): all requirements found, attempting install
  waited 199.044471ms for CSV operator-group-e2e-smz2l-vv7fx/another-csv-xtrdv: to be in phases [Failed], in phase InstallReady (AllRequirementsMet): all requirements found, attempting install
  14:29:41.6321: Failed (InstallComponentFailedNoRetry): install strategy failed: install strategy failed: deployments.apps "operator-deployment8b7mg" is forbidden: User "system:serviceaccount:operator-group-e2e-smz2l-vv7fx:nginx-sak98h5" cannot get resource "deployments" in API group "apps" in the namespace "operator-group-e2e-smz2l-vv7fx"
  waited 200.980766ms for CSV operator-group-e2e-smz2l-vv7fx/another-csv-xtrdv: to be in phases [Failed], in phase Failed (InstallComponentFailedNoRetry): install strategy failed: install strategy failed: deployments.apps "operator-deployment8b7mg" is forbidden: User "system:serviceaccount:operator-group-e2e-smz2l-vv7fx:nginx-sak98h5" cannot get resource "deployments" in API group "apps" in the namespace "operator-group-e2e-smz2l-vv7fx"
  14:29:41.6377: wait for CSV to succeeed
  14:29:41.8324: Failed (InstallComponentFailedNoRetry): install strategy failed: install strategy failed: deployments.apps "operator-deployment8b7mg" is forbidden: User "system:serviceaccount:operator-group-e2e-smz2l-vv7fx:nginx-sak98h5" cannot get resource "deployments" in API group "apps" in the namespace "operator-group-e2e-smz2l-vv7fx"
  waited 7.277033202s for CSV operator-group-e2e-smz2l-vv7fx/another-csv-xtrdv: to be in phases [Succeeded], in phase Failed (InstallComponentFailedNoRetry): install strategy failed: install strategy failed: deployments.apps "operator-deployment8b7mg" is forbidden: User "system:serviceaccount:operator-group-e2e-smz2l-vv7fx:nginx-sak98h5" cannot get resource "deployments" in API group "apps" in the namespace "operator-group-e2e-smz2l-vv7fx"
  14:29:42.0323: Failed (InstallComponentFailedNoRetry): install strategy failed: install strategy failed: deployments.apps "operator-deployment8b7mg" is forbidden: User "system:serviceaccount:operator-group-e2e-smz2l-vv7fx:nginx-sak98h5" cannot get resource "deployments" in API group "apps" in the namespace "operator-group-e2e-smz2l-vv7fx"

< ... repeated N times ... >

   14:34:42.0321: Failed (InstallComponentFailedNoRetry): install strategy failed: install strategy failed: deployments.apps "operator-deployment8b7mg" is forbidden: User "system:serviceaccount:operator-group-e2e-smz2l-vv7fx:nginx-sak98h5" cannot get resource "deployments" in API group "apps" in the namespace "operator-group-e2e-smz2l-vv7fx"
  [FAILED] in [It] - /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:1746 @ 11/14/23 14:34:42.147
  cleaning up ephemeral test resources...
  deleting test subscriptions...
  deleting test installplans...
  deleting test catalogsources...
  deleting test crds...
  deleting test csvs...
  test resources deleted
  << Timeline

  [FAILED] 
  	Error Trace:	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:1746
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863
  	            				/opt/hostedtoolcache/go/1.20.10/x64/src/runtime/asm_amd64.s:1598
  	Error:      	Received unexpected error:
  	            	timed out waiting for the condition
  	Test:       	Operator Group insufficient permissions resolve via RBAC
  
  In [It] at: /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:1746 @ 11/14/23 14:34:42.147

  Full Stack Trace
    github.com/stretchr/testify/require.NoError({0x7f98740e1188, 0xc000df2ab0}, {0x4090400, 0xc0001b8150}, {0x0, 0x0, 0x0})
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:1357 +0x96
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.9()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:1746 +0x15b5
```

**Comment by tmshort** [comment] 2023-11-30 14:43
Duplicate of #3091

**Closed by tmshort** 2023-11-30 14:43 UTC
Labels: kind/flake
