### ISSUE TITLE
Problem with deleting operators prometheus and grafana.

### ISSUE THREAD

**Issue by marcusnh** [operator-framework/operator-lifecycle-manager#2867] opened 2022-09-28 08:02 UTC
## Bug Report

**What did you do?**

- I installed olm v0.22 through the operator-sdk:  operator-sdk olm install
- Used kubernetes to create the two operators with  two subscription and one operatorgroups into a namespace observability, with the following instances of prometheus and grafana. 
```
root@test:~$ k get operators
NAME                             AGE
grafana-operator.observability   16h
prometheus.observability         30m
``` 
- Had problems running both operators through the same operatorgroup, so tried to remove everything and start all over again.
- Removed the subscriptions, csv, ip, operatorGroup and removed the operators, but the operators spinn back up immedately. 
- Tried to uninstall and install olm, but the two operators get installed with olm
```
root@test:~$ k delete operators grafana-operator.observability
operator.operators.coreos.com "grafana-operator.observability" deleted
root@testt:~$ k delete operators prometheus.observability
operator.operators.coreos.com "prometheus.observability" deleted
root@testt:~$ k get operators
NAME                             AGE
grafana-operator.observability   7s
prometheus.observability         2s
root@test:~$ k get operatorgroup -A
NAMESPACE   NAME               AGE
olm         olm-operators      16h
operators   global-operators   16h
root@test:~$ k delete operators prometheus.observability ^C
root@testt:~$ k get sub -A
No resources found
root@testt:~$ k get csv -A
NAMESPACE   NAME            DISPLAY          VERSION   REPLACES   PHASE
olm         packageserver   Package Server   0.22.0               Succeeded
root@test:~$ k get ip -A
No resources found
```

**Environment**
- operator SDK:
```
$ operator-sdk version
operator-sdk version: "v1.23.0", commit: "1eaeb5adb56be05fe8cc6dd70517e441696846a4", kubernetes version: "1.24.2", go version: "go1.18.5", GOOS: "linux", GOARCH: "amd64"
```

- * Kubernetes version information:
```
$ kubectl version --short
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.22.9+vmware.1
```

**Possible Solution**

**Comment by marcusnh** [comment] 2022-09-28 08:32
Similar to this issue: [https://bugzilla.redhat.com/show_bug.cgi?id=1899588], but the suggested solution did not work

**Comment by awgreene** [comment] 2022-09-28 14:34
Please review [this documentation](https://github.com/operator-framework/olm-docs/pull/251/files#diff-223f6168902b7fd321583c8a7a038e8361d8f4205d6bcf194a36ce3c563e1d50R71) on how to fully uninstall an operator. I'm going to close this as I believe it is working as intended, but feel free to reopen if the issue persists.

**Closed by awgreene** 2022-09-28 14:34 UTC
Labels: kind/bug
