### ISSUE TITLE
Operator deployment resources claimed in CSV aren't passed into the operator deployment

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-lifecycle-manager#1940] opened 2021-01-06 16:57 UTC
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

I try to deploy an Operator into the Openshift cluster. After the operator is deployed, I found the `.spec.containers[].resources` claimed in the `csv.spec.install.deployments` are not added in the operator deployment.
 
For example,
CSV:
```
  install:
    spec:
      deployments:
       ...
                resources:
                  limits:
                    cpu: 200m
                    memory: 256Mi
                  requests:
                    cpu: 200m
                    memory: 256Mi
```
Deployment:
```
    spec:
    ...
      containers:
       ...
        - resources: {}
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

I expect the deployment `resources` added into the CSV can be added into operator deployment during the installation.
 
**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

The resources field is empty in the operator deployment. 

**Environment**
* operator-lifecycle-manager version:
0.15.1

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+ca4017d", GitCommit:"ca4017d", GitTreeState:"clean", BuildDate:"2020-11-14T01:37:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
OCP
**Possible Solution**

**Additional context**

**Comment by horis233** [comment] 2021-01-07 20:44
@awgreene

I believe we shouldn't overwrite the resource field if the config for resources is empty in the subscription. 

```
// InjectResourcesIntoDeployment will inject provided Resources
// into given podSpec
//
// If podSpec already defines Resources, it will be overwritten
func InjectResourcesIntoDeployment(podSpec *corev1.PodSpec, resources corev1.ResourceRequirements) error {
	if podSpec == nil {
		return errors.New("no pod spec provided")
	}

	for i := range podSpec.Containers {
		container := &podSpec.Containers[i]
		container.Resources = resources
	}

	return nil
}
```

We should add 
```
if resources == nil {
  return nil
}
```

I believe other inject functions should have this check as well.

**Comment by matskiv** [comment] 2021-01-28 15:25
This looks like a duplicate of #1912

**Comment by horis233** [comment] 2021-01-28 15:48
@matskiv Thanks for pointing it out. I will close this one

**Closed** 2021-03-04 17:28 UTC
Labels: kind/bug
