### ISSUE TITLE
InstallPlan creates a Service without setting an OwnerReference

### ISSUE THREAD

**Issue by balpert89** [operator-framework/operator-lifecycle-manager#1747] opened 2020-09-02 09:32 UTC
## Bug Report

**What did you do?**
I am bundling a `Service` and a `ServiceMonitor` resource in my OLM version to enable metrics scraping. OLM picks this up correctly, but it does not set an `ownerReferences` in the created `Service` resource. On the `ServiceMonitor` resource the `ownerReferences` field is created correctly.

**What did you expect to see?**
An `ownerReferences` field on the created `Service` resource.

**What did you see instead? Under which circumstances?**
There is no `ownerReferences` field on the created `Service` resource.

### Service resource
```
kind: Service
apiVersion: v1
metadata:
  name: mcs-helloworld-operator-metrics-5007135952
  namespace: mcs-operators
  selfLink: >-
    /api/v1/namespaces/mcs-operators/services/mcs-helloworld-operator-metrics-5007135952
  uid: 03c98ead-cd58-41fc-a7a0-4895a3fedc94
  resourceVersion: '178766761'
  creationTimestamp: '2020-09-02T08:26:30Z'
  labels:
    name: mcs-helloworld-operator
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8383
      targetPort: 8383
  selector:
    name: mcs-helloworld-operator
  clusterIP: 172.30.158.93
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
```

### ServiceMonitor resource
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  selfLink: >-
    /apis/monitoring.coreos.com/v1/namespaces/mcs-operators/servicemonitors/mcs-helloworld-operator-metrics-5007135952
  resourceVersion: '178766759'
  name: mcs-helloworld-operator-metrics-5007135952
  uid: 33166e25-4c6d-4080-a978-c01738379791
  creationTimestamp: '2020-09-02T08:26:30Z'
  generation: 1
  namespace: mcs-operators
  ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: ClusterServiceVersion
      name: mcs-helloworld.v2.0.21
      uid: 729fe6ed-fea8-414d-b996-5c81476a9675
  labels:
    name: mcs-helloworld-operator
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      port: http-metrics
  namespaceSelector: {}
  selector:
    matchLabels:
      name: mcs-helloworld-operator
```

**Environment**
* operator-lifecycle-manager version: v0.14.2

* Kubernetes version information: OpenShift 4.4 (k8s 1.17) and 4.5 (k8s 1.18)

* Kubernetes cluster kind: OCP

**Comment by exdx** [comment] 2020-09-18 14:55
This is a bug in OLM 0.14.2, where we check the owner refs but don't add one explicitly per https://github.com/operator-framework/operator-lifecycle-manager/blob/99643127d862c3331c6965e6ff0019bb564d2d4c/pkg/controller/operators/catalog/operator.go#L1685

In 0.16.1 we add the owner ref to the CSV first, per https://github.com/operator-framework/operator-lifecycle-manager/blob/fddbf04ca175fb407fce5c39c3c651a11f74c2d5/pkg/controller/operators/catalog/operator.go#L1801 and also added a test to check for this when deleting the object (deleting the CSV should delete the service). 

My suggestion is to update to the newer version of OLM if you're affected by this issue

**Comment by timflannagan** [comment] 2022-02-11 20:35
It looks like Dan already triaged this was an issue with an older OLM minor version release, so I'm going to close this out. Let's re-open this issue if we can still reproduce using a newer OLM minor version release that's supported.

**Closed by timflannagan** 2022-02-11 20:35 UTC
Labels: kind/bug, triage/unresolved
