### ISSUE TITLE
Failed to update catalog source `rh-operators` status

### ISSUE THREAD

**Issue by Evalle** [operator-framework/operator-lifecycle-manager#544] opened 2018-10-30 15:40 UTC
Hello there, I just installed OLM on the new k8s cluster and I can see this log message from the `olm-operator` pod

```bash
kubectl logs -f -n olm catalog-operator-54ddc48bd-jgqfp
time="2018-10-30T15:23:37Z" level=info msg="Using in-cluster kube client config"
time="2018-10-30T15:23:37Z" level=info msg="Using in-cluster kube client config"
time="2018-10-30T15:23:37Z" level=info msg="connection established. cluster-version: v1.10.0"
time="2018-10-30T15:23:37Z" level=info msg="operator ready"
time="2018-10-30T15:23:37Z" level=info msg="starting informers..."
time="2018-10-30T15:23:37Z" level=info msg="waiting for caches to sync..."
time="2018-10-30T15:23:37Z" level=info msg="olm/rh-operators added"
time="2018-10-30T15:23:37Z" level=info msg="starting workers..."
time="2018-10-30T15:23:37Z" level=info msg="getting from queue" key=olm/rh-operators queue=catsrc
time="2018-10-30T15:23:37Z" level=info msg="retrying olm/rh-operators"
E1030 15:23:37.631372       1 queueinformer_operator.go:136] Sync "olm/rh-operators" failed: failed to update catalog source rh-operators status: the server could not find the requested resource (put catalogsources.operators.coreos.com rh-operators)
time="2018-10-30T15:23:37Z" level=info msg="getting from queue" key=olm/rh-operators queue=catsrc
time="2018-10-30T15:23:37Z" level=info msg="retrying olm/rh-operators"
E1030 15:23:37.655494       1 queueinformer_operator.go:136] Sync "olm/rh-operators" failed: failed to update catalog source rh-operators status: the server could not find the requested resource (put catalogsources.operators.coreos.com rh-operators)
time="2018-10-30T15:23:37Z" level=info msg="getting from queue" key=olm/rh-operators queue=catsrc
time="2018-10-30T15:23:37Z" level=info msg="retrying olm/rh-operators"
E1030 15:23:37.693061       1 queueinformer_operator.go:136] Sync "olm/rh-operators" failed: failed to update catalog source rh-operators status: the server could not find the requested resource (put catalogsources.operators.coreos.com rh-operators)
time="2018-10-30T15:23:37Z" level=info msg="getting from queue" key=olm/rh-operators queue=catsrc
time="2018-10-30T15:23:37Z" level=info msg="retrying olm/rh-operators"
E1030 15:23:37.736738       1 queueinformer_operator.go:136] Sync "olm/rh-operators" failed: failed to update catalog source rh-operators status: the server could not find the requested resource (put catalogsources.operators.coreos.com rh-operators)
time="2018-10-30T15:23:37Z" level=info msg="getting from queue" key=olm/rh-operators queue=catsrc
time="2018-10-30T15:23:37Z" level=info msg="retrying olm/rh-operators"
E1030 15:23:37.798421       1 queueinformer_operator.go:136] Sync "olm/rh-operators" failed: failed to update catalog source rh-operators status: the server could not find the requested resource (put catalogsources.operators.coreos.com rh-operators)
time="2018-10-30T15:23:37Z" level=info msg="getting from queue" key=olm/rh-operators queue=catsrc
```
Can you give me any hint of how can i debug this issue? Thanks in advance! 

### Environment
- Kuberentes v1.10 
- OLM ver 0.7.4

**Comment by Evalle** [comment] 2018-11-01 13:10
Hey @njhale  thank you for the answer, here the output from the installation with k8s v1.11
```bash
$ 
$ kubectl create -f deploy/upstream/manifests/latest/
namespace "olm" created
clusterrole "system:controller:operator-lifecycle-manager" created
serviceaccount "olm-operator-serviceaccount" created
clusterrolebinding "olm-operator-binding-olm" created
configmap "rh-operators" created
deployment "olm-operator" created
deployment "catalog-operator" created
clusterrole "aggregate-olm-edit" created
clusterrole "aggregate-olm-view" created
apiservice "v1alpha1.packages.apps.redhat.com" created
clusterrolebinding "packagemanifest:system:auth-delegator" created
rolebinding "packagemanifest-auth-reader" created
clusterrolebinding "packagemanifest-view" created
clusterrolebinding "package-apiserver-clusterrolebinding" created
secret "package-server-certs" created
deployment "package-server" created
service "package-server" created
error validating "deploy/upstream/manifests/latest/0000_30_02-clusterserviceversion.crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.subresources.status): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceSubresourceStatus: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.apiservicedefinitions.properties.owned.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.apiservicedefinitions.properties.required.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.customresourcedefinitions.properties.owned.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.customresourcedefinitions.properties.required.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.icon.properties.mediatype.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.icon.properties.mediatype.enum[1]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.icon.properties.mediatype.enum[2]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.icon.properties.mediatype.enum[3]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[0].properties.strategy.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[1].properties.spec.properties.clusterPermissions.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[1].properties.spec.properties.deployments.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[1].properties.spec.properties.permissions.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.install.oneOf[1].properties.strategy.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.keywords.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.links.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maintainers.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[1]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[2]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[3]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[4]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[5]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[6]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.maturity.enum[7]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.selector.properties.matchExpressions.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected ""]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "deploy/upstream/manifests/latest/0000_30_03-installplan.crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.subresources.status): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceSubresourceStatus: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.anyOf[0].properties.approval.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.anyOf[1].properties.approval.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.clusterServiceVersionNames.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected ""]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "deploy/upstream/manifests/latest/0000_30_04-subscription.crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.subresources.status): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceSubresourceStatus: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.installPlanApproval.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.installPlanApproval.enum[1]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected ""]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "deploy/upstream/manifests/latest/0000_30_05-catalogsource.crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.subresources.status): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceSubresourceStatus: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.secrets.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got "map", expected "", ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.sourceType.enum[0]): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON: got "string", expected ""]; if you choose to ignore these errors, turn validation off with --validate=false
unable to recognize "deploy/upstream/manifests/latest/0000_30_09-rh-operators.catalogsource.yaml": no matches for operators.coreos.com/, Kind=CatalogSource
```

**Comment by njhale** [comment] 2018-11-20 14:18
@Evalle Sorry for the delayed response. We've made a couple of releases since this issue was created. You may be able to install v0.8.0. I can confirm it's working with minikube v0.30.0.

**Comment by ecordell** [comment] 2018-12-10 23:14
Fairly certain this issue is resolved - closing for now, we can re-open if we find it's not fixed.

**Closed by ecordell** 2018-12-10 23:14 UTC
